name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - name: Install dependencies
      run: npm ci
    # - name: Svelte Check
    #   run: npm run check
    - name: Format
      run: npm run prettier:dry
    - name: Build
      run: npm run build